"""
BidVex — Escrow + Pickup Code Service
Non-vehicle items only. Holds funds until pickup code confirmation.
"""
import re
import secrets
import stripe
import os
import logging
from datetime import datetime, timezone, timedelta
from fastapi import HTTPException

logger = logging.getLogger(__name__)

stripe.api_key = os.environ.get("STRIPE_API_KEY")

# Safe alphabet: excludes 0, O, I, 1, L to avoid confusion. Legacy escrow
# transactions issued 6-char codes from this alphabet; new codes use the
# canonical `BVX-XXXXXXXX` format below.
PICKUP_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


# ──────────────────────────────────────────────────────────────────
# iter455 — Canonical pickup-code shared helpers
# ──────────────────────────────────────────────────────────────────
# All pickup codes issued from Feb 2026 onward use the canonical form
# `BVX-XXXXXXXX` (BVX- prefix + 8 uppercase alphanumerics), matching the
# codes generated by routes/transaction_pickup_code.py and rendered on
# the buyer's receipt / BuyerDashboard.
#
# Legacy 6-character codes stored on older `escrow_transactions` rows
# remain valid — the normalized comparison strips punctuation + case so
# both formats resolve to the same canonical byte-string when the seller
# enters them (with or without hyphen, spaces, or lowercase).

def normalize_pickup_code(raw: str) -> str:
    """Strip whitespace + hyphens + non-alphanumeric, uppercase.

    Used on BOTH the user input and the stored code before comparison so
    that ``BVX-ARKC661T`` / ``bvxarkc661t`` / ``BVX ARKC 661T`` all
    resolve to the same string ``BVXARKC661T`` and match the stored
    canonical code.
    """
    if not raw:
        return ""
    return re.sub(r"[^A-Z0-9]", "", str(raw).strip().upper())


async def generate_pickup_code(db) -> str:
    """Generates a collision-safe canonical `BVX-XXXXXXXX` pickup code.

    iter455 — unified with routes/transaction_pickup_code.generate_pickup_code
    so buyers and sellers see the same format across every surface.
    """
    for _ in range(100):
        body = "".join(secrets.choice(PICKUP_ALPHABET) for _ in range(8))
        code = f"BVX-{body}"
        existing = await db.escrow_transactions.find_one(
            {"pickup_code": code, "escrow_status": "held"}
        )
        if not existing:
            return code
    raise RuntimeError("Failed to generate unique pickup code after 100 attempts")


async def create_escrow_hold(
    db,
    auction_id: str,
    listing_id: str,
    buyer_id: str,
    seller_id: str,
    hammer_price_cents: int,
    total_charged_cents: int,
    application_fee_cents: int,
    stripe_payment_intent_id: str,
    province: str,
) -> dict:
    """
    Called after payment_intent.succeeded for non-vehicle items.
    Funds held on BidVex platform — NO transfer to seller yet.

    iter455 — When a `transactions.pickup_code` (BVX-XXXXXXXX) already
    exists for this auction (issued by services/payment_collection.py
    when the buyer's Stripe charge cleared), we REUSE that code so both
    documents converge on the same pickup code. The buyer's receipt +
    the seller's escrow row therefore always agree.
    """
    # Prefer an existing BVX code from the transactions collection.
    txn_row = await db.transactions.find_one(
        {"$or": [
            {"listing_id": auction_id, "pickup_code": {"$exists": True, "$ne": None}},
            {"pickup_code_listing_id": auction_id, "pickup_code": {"$exists": True, "$ne": None}},
            {"auction_id": auction_id, "pickup_code": {"$exists": True, "$ne": None}},
        ]},
        {"_id": 0, "pickup_code": 1},
    )
    if txn_row and txn_row.get("pickup_code"):
        pickup_code = txn_row["pickup_code"]
    else:
        pickup_code = await generate_pickup_code(db)
    now = datetime.now(timezone.utc)
    expires_at = now + timedelta(hours=48)

    escrow = {
        "auction_id": auction_id,
        "listing_id": listing_id,
        "buyer_id": buyer_id,
        "seller_id": seller_id,
        "hammer_price_cents": hammer_price_cents,
        "total_charged_cents": total_charged_cents,
        "application_fee_cents": application_fee_cents,
        "stripe_payment_intent_id": stripe_payment_intent_id,
        "stripe_transfer_id": None,
        "escrow_status": "held",
        "pickup_code": pickup_code,
        "pickup_code_expires_at": expires_at.isoformat(),
        "pickup_code_entered_at": None,
        "pickup_confirmed_at": None,
        "funds_released_at": None,
        "auto_release_scheduled_at": expires_at.isoformat(),
        "created_at": now.isoformat(),
        "updated_at": now.isoformat(),
        "item_type": "non_vehicle",
        "province": province,
    }

    await db.escrow_transactions.insert_one(escrow)
    escrow.pop("_id", None)

    # Send pickup code email to buyer
    try:
        buyer = await db.users.find_one({"id": buyer_id}, {"_id": 0, "email": 1, "name": 1, "preferred_language": 1, "language_preference": 1})
        seller_doc = await db.users.find_one({"id": seller_id}, {"_id": 0, "name": 1})
        if buyer and buyer.get("email"):
            from services.email_service import send_pickup_code_email
            await send_pickup_code_email(
                buyer=buyer,
                seller=seller_doc or {"name": "Seller"},
                pickup_code=pickup_code,
                auction_id=auction_id,
                expires_at=expires_at.strftime("%B %d, %Y at %I:%M %p UTC"),
            )
            logger.info(f"[ESCROW] Pickup code email sent to {buyer['email']}")
    except Exception as e:
        logger.error(f"[ESCROW] Failed to send pickup code email: {e}")

    logger.info(f"[ESCROW] Created hold for auction {auction_id}, code={pickup_code}, expires={expires_at}")
    return escrow


async def _resolve_paid_order_record(
    db, *, auction_id: str, seller_id: str
):
    """iter469 — Canonical paid-order resolver.

    The transaction/order row is the canonical paid-order identity;
    ``pickup_code`` is the buyer's authorization credential. Both the
    seller dashboard (``get_seller_escrow_status``) and pickup
    confirmation must resolve the SAME record for ``(auction_id,
    seller_id)`` before validating the buyer's code.

    Returns a tuple ``(source, record)`` where ``source`` is
    ``"escrow"`` (canonical row in ``escrow_transactions``) or
    ``"transaction"`` (fallback row in ``transactions``). When neither
    collection has a match, returns ``(None, None)``.

    Guardrails (per iter469 directive):
    - Enforces seller identity as a matching constraint — the caller
      cannot resolve another seller's order via ``auction_id`` alone.
    - Ignores rows that are already released / auto-released / refunded
      (one-time-use) so the caller can decide the correct error code.
    - Ignores confirmed transactions (``pickup_code_confirmed_at``
      set) for the same reason.
    """
    esc = await db.escrow_transactions.find_one(
        {
            "auction_id": auction_id,
            "seller_id": seller_id,
            "escrow_status": {"$in": ["held", "disputed"]},
        },
        {"_id": 0},
    )
    if esc:
        return "escrow", esc

    # Fallback — a paid `transactions` row seeded by
    # `services/payment_collection.finalize_auction_payment` that never
    # got a matching `escrow_transactions` row. Match seller identity
    # via either the top-level `seller_id` or `pickup_code_seller_id`
    # (the code-lookup index). Rows already stamped
    # `pickup_code_confirmed_at` are treated as consumed (one-time-use).
    tx = await db.transactions.find_one(
        {
            "$or": [
                {"listing_id": auction_id},
                {"pickup_code_listing_id": auction_id},
                {"auction_id": auction_id},
            ],
            "pickup_code": {"$exists": True, "$ne": None},
            "$and": [
                {"$or": [{"seller_id": seller_id}, {"pickup_code_seller_id": seller_id}]},
                {"$or": [{"pickup_code_confirmed_at": None}, {"pickup_code_confirmed_at": {"$exists": False}}]},
            ],
        },
        {"_id": 0},
    )
    if tx:
        return "transaction", tx
    return None, None


# ── iter470 — Payout-state resolver ────────────────────────────────
#
# Four distinct states — a missing payout row is NOT "failed":
#   * ``sent``    — real ``stripe_transfer_id`` on the seller_payouts row
#   * ``pending`` — seller_payouts row exists with status ``pending`` /
#                   ``payout_pending`` (or a pending_payouts queue row
#                   exists) but no transfer reference
#   * ``failed``  — seller_payouts row exists with an explicit failure
#                   status (``failed`` / ``error``)
#   * ``unknown`` — NO payout record exists yet for this listing
#                   (payout not created, missing evidence — not
#                   equivalent to failed)
#
# Critical rule (per iter470 directive): a missing escrow record must
# NEVER be treated as proof that a seller payout was already sent, and
# a missing payout record must NEVER be treated as failed.

async def _resolve_payout_state(
    db, *, listing_id: str, seller_id: str, lot_number=None,
):
    """Return ``(state, payout_row)`` where ``state`` is one of
    ``sent`` / ``pending`` / ``failed`` / ``unknown``.

    Consults the ``seller_payouts`` collection primarily (written by
    ``services/seller_payouts.process_seller_payout``). Falls back to
    the ``pending_payouts`` queue for the pending signal.
    """
    query = {"listing_id": listing_id, "seller_id": seller_id}
    if lot_number is not None:
        query["lot_number"] = lot_number
    payout = await db.seller_payouts.find_one(query, {"_id": 0})
    if payout:
        status = str(payout.get("status") or "").lower()
        transfer_id = payout.get("stripe_transfer_id")
        if status == "sent" and transfer_id:
            return "sent", payout
        if status in {"pending", "payout_pending"}:
            return "pending", payout
        if status in {"failed", "error"}:
            return "failed", payout
        # Unexpected state — err on the side of caution, treat as unknown.
        return "unknown", payout

    # No seller_payouts row — check the pending_payouts queue (older
    # `finalize_auction_payment` fallback wrote here first).
    pending_query = {"listing_id": listing_id, "seller_id": seller_id}
    if lot_number is not None:
        pending_query["lot_number"] = lot_number
    pending_row = await db.pending_payouts.find_one(pending_query, {"_id": 0})
    if pending_row:
        return "pending", pending_row

    return "unknown", None


def _payout_state_response(*, payout_state, amount_cad, transfer_id):
    """Compose the confirm-pickup response body for a given payout state.

    Messages are deliberately narrow (no promises about timing when the
    payout has not shipped) so the seller UI reflects the exact state.
    """
    amount_str = f"${float(amount_cad):.2f} CAD"
    if payout_state == "sent" and transfer_id:
        return {
            "status": "released",
            "payout_state": "sent",
            "transfer_id": transfer_id,
            "amount_released": amount_str,
            "message_en": "Pickup confirmed. Funds have been released.",
            "message_fr": "Retrait confirmé. Les fonds ont été libérés.",
        }
    if payout_state == "pending":
        return {
            "status": "pickup_confirmed_payout_pending",
            "payout_state": "pending",
            "transfer_id": None,
            "amount_pending": amount_str,
            "message_en": "Pickup confirmed. Payout is pending.",
            "message_fr": "Retrait confirmé. Le versement est en attente.",
        }
    if payout_state == "failed":
        return {
            "status": "pickup_confirmed_payout_review",
            "payout_state": "failed",
            "transfer_id": None,
            "amount_pending": amount_str,
            "message_en": "Pickup confirmed. Payout requires review.",
            "message_fr": "Retrait confirmé. Le versement doit être vérifié.",
        }
    # unknown / not created
    return {
        "status": "pickup_confirmed_payout_review",
        "payout_state": "unknown",
        "transfer_id": None,
        "amount_pending": amount_str,
        "message_en": "Pickup confirmed. Payout requires review.",
        "message_fr": "Retrait confirmé. Le versement doit être vérifié.",
    }


async def confirm_pickup(db, seller_id: str, auction_id: str, code: str) -> dict:
    """
    Seller enters the pickup code. Validates and releases funds.

    iter455 — Accepts lowercase, spaces, hyphens, or plain 8/12-char
    strings. The stored code AND the user input are normalized (strip
    non-alphanumeric + uppercase) before comparison so `BVX-ARKC661T`,
    `bvxarkc661t`, `BVX ARKC 661T`, and legacy 6-char codes all match
    when the underlying alphanumeric matches.

    iter469 — Resolves the canonical paid-order record for
    ``(auction_id, seller_id)`` BEFORE validating the buyer's code.
    The pickup code is the buyer's authorization credential — it is
    NOT the record identity. If the paid order lives in the
    ``transactions`` collection (no ``escrow_transactions`` row,
    happens for orders settled via
    ``services/payment_collection.finalize_auction_payment`` prior to
    the forward fix), we still validate the code, expiry, and
    one-time-use rules, and follow the existing payout rules — but we
    do NOT trigger a second Stripe transfer because
    ``process_seller_payout`` already dispatched the funds at
    settlement time.
    """
    input_norm = normalize_pickup_code(code)
    if not input_norm:
        raise HTTPException(status_code=400, detail={
            "error": "invalid_code",
            "message_en": "Enter the pickup code from the buyer's receipt (e.g. BVX-XXXXXXXX).",
            "message_fr": "Entrez le code de retrait figurant sur le reçu de l'acheteur (ex. BVX-XXXXXXXX).",
        })

    # ── Canonical resolution ─────────────────────────────────────
    source, record = await _resolve_paid_order_record(
        db, auction_id=auction_id, seller_id=seller_id,
    )
    if not record:
        # No held escrow AND no unconfirmed transaction row → 404. Also
        # covers the wrong-seller / wrong-auction cases (the resolver
        # filters by both). We additionally check whether an already-
        # confirmed row exists for this (auction, seller) so the seller
        # sees an "already confirmed" error instead of a generic 404.
        already = await db.transactions.find_one(
            {
                "$or": [
                    {"listing_id": auction_id},
                    {"pickup_code_listing_id": auction_id},
                    {"auction_id": auction_id},
                ],
                "$and": [
                    {"$or": [{"seller_id": seller_id}, {"pickup_code_seller_id": seller_id}]},
                ],
                "pickup_code_confirmed_at": {"$ne": None},
            },
            {"_id": 0, "pickup_code_confirmed_at": 1},
        )
        if not already:
            already_esc = await db.escrow_transactions.find_one(
                {
                    "auction_id": auction_id,
                    "seller_id": seller_id,
                    "escrow_status": {"$in": [
                        "released", "auto_released", "refunded",
                        # iter470 — this new state also counts as
                        # already-confirmed for one-time-use rules.
                        "pickup_confirmed_payout_pending",
                    ]},
                },
                {"_id": 0, "funds_released_at": 1, "escrow_status": 1, "pickup_confirmed_at": 1},
            )
            if already_esc:
                already = {"pickup_code_confirmed_at": already_esc.get("funds_released_at") or already_esc.get("pickup_confirmed_at")}
        if already:
            raise HTTPException(status_code=409, detail={
                "error": "already_confirmed",
                "confirmed_at": already.get("pickup_code_confirmed_at"),
                "message_en": "This pickup code was already confirmed.",
                "message_fr": "Ce code a déjà été confirmé.",
            })
        raise HTTPException(status_code=404, detail={
            "error": "escrow_not_found",
            "message_en": "No active escrow found for this auction.",
            "message_fr": "Aucun dépôt actif trouvé pour cette enchère.",
        })

    # ── Code validation (only AFTER canonical resolution) ────────
    stored_norm = normalize_pickup_code(record.get("pickup_code", ""))
    if not stored_norm or stored_norm != input_norm:
        await _log_failed_attempt(db, auction_id, seller_id, input_norm)
        raise HTTPException(status_code=400, detail={
            "error": "invalid_code",
            "message_en": "Invalid pickup code. Please ask the buyer to check their email.",
            "message_fr": "Code de retrait invalide. Veuillez demander à l'acheteur de vérifier son courriel.",
        })
    # Use the stored (canonical) code for downstream ops so audit trails
    # record the exact value that was on the receipt.
    code = record["pickup_code"]

    # ── Expiry (best-effort, only when the record carries an expiry) ──
    expires_at_raw = record.get("pickup_code_expires_at")
    if expires_at_raw:
        expires_at = expires_at_raw
        if isinstance(expires_at, str):
            try:
                expires_at = datetime.fromisoformat(expires_at.replace("Z", "+00:00"))
            except ValueError:
                expires_at = None
        if isinstance(expires_at, datetime) and datetime.now(timezone.utc) > expires_at:
            raise HTTPException(status_code=410, detail={
                "error": "code_expired",
                "message_en": "This pickup code has expired. Funds have been auto-released.",
                "message_fr": "Ce code de retrait a expiré. Les fonds ont été libérés automatiquement.",
            })

    # ── Path A: escrow_transactions canonical row ─────────────────
    if source == "escrow":
        # iter470 — Consult payout state FIRST. Never attempt a second
        # Stripe transfer if a prior `seller_payouts` row already carries
        # a real transfer reference. Never claim "funds released" for
        # pending / failed payout states.
        lot_no = record.get("lot_number")
        payout_state, payout_row = await _resolve_payout_state(
            db, listing_id=record.get("listing_id") or auction_id,
            seller_id=seller_id, lot_number=lot_no,
        )

        seller = await db.users.find_one({"id": seller_id}, {"_id": 0, "stripe_connect_account_id": 1})
        connect_id = (seller or {}).get("stripe_connect_account_id")
        seller_payout_cents = record["total_charged_cents"] - record["application_fee_cents"]

        if payout_state == "sent":
            # A prior payout already shipped funds. Reuse its transfer id
            # and skip `stripe.Transfer.create` entirely.
            transfer_id = (payout_row or {}).get("stripe_transfer_id")
        elif payout_state in {"pending", "failed"}:
            # Do NOT create a second payout obligation. The existing
            # pending/failed payout survives untouched.
            transfer_id = None
        else:
            # payout_state == "unknown" — no payout record exists yet.
            # For the ESCROW row path this is the classic "release funds
            # via escrow" flow: attempt Stripe transfer. For the
            # transactions-only fallback we never attempt a transfer
            # here (that path is handled in Path B below and has no
            # escrow-hold guarantee that funds are on-platform).
            transfer_id = None
            if connect_id and seller_payout_cents > 0:
                try:
                    transfer = stripe.Transfer.create(
                        amount=seller_payout_cents,
                        currency="cad",
                        destination=connect_id,
                        metadata={
                            "type": "escrow_release",
                            "auction_id": auction_id,
                            "pickup_code": code,
                            "released_by": "seller_code_entry",
                        },
                        idempotency_key=f"escrow-release-{auction_id}-{seller_id}",
                    )
                    transfer_id = transfer.id
                except Exception as e:
                    logger.error(f"[ESCROW] Transfer failed for {auction_id}: {e}")
                    raise HTTPException(status_code=500, detail="Transfer failed. Please contact support.")

        now = datetime.now(timezone.utc).isoformat()
        # iter470 — Only mark the escrow row `released` when funds
        # actually shipped (transfer_id from Stripe now, OR reused from
        # a prior `sent` payout row). Otherwise flip to
        # `pickup_confirmed_payout_pending` so the dashboard reflects
        # the accurate state.
        funds_shipped = bool(transfer_id) or payout_state == "sent"
        target_status = "released" if funds_shipped else "pickup_confirmed_payout_pending"
        update_fields = {
            "escrow_status": target_status,
            "stripe_transfer_id": transfer_id,
            "pickup_code_entered_at": now,
            "pickup_confirmed_at": now,
            "updated_at": now,
            "payout_state": "sent" if funds_shipped else payout_state,
        }
        if funds_shipped:
            update_fields["funds_released_at"] = now
        result = await db.escrow_transactions.update_one(
            {"auction_id": auction_id, "seller_id": seller_id, "escrow_status": "held"},
            {"$set": update_fields},
        )
        # Also stamp the paired transactions row (if any) so the union
        # dashboard reflects the confirmation state consistently.
        try:
            await db.transactions.update_many(
                {
                    "$or": [
                        {"listing_id": auction_id},
                        {"pickup_code_listing_id": auction_id},
                        {"auction_id": auction_id},
                    ],
                    "$and": [
                        {"$or": [{"seller_id": seller_id}, {"pickup_code_seller_id": seller_id}]},
                    ],
                    "pickup_code_confirmed_at": None,
                },
                {"$set": {
                    "pickup_code_confirmed_at": now,
                    "pickup_code_confirmed_by": seller_id,
                    "payment_confirmed": True,
                }},
            )
        except Exception as e:  # noqa: BLE001
            logger.warning(f"[ESCROW] transactions mirror update failed for {auction_id}: {e}")

        if result.modified_count == 0:
            # Row was already released by a concurrent confirm — treat as
            # one-time-use and return the already-confirmed error.
            raise HTTPException(status_code=409, detail={
                "error": "already_confirmed",
                "message_en": "This pickup code was already confirmed.",
                "message_fr": "Ce code a déjà été confirmé.",
            })

        # iter470 — Return the accurate response based on actual payout
        # state. Never say "released" without a real transfer_id.
        amount_cad = seller_payout_cents / 100
        effective_state = "sent" if funds_shipped else payout_state
        response = _payout_state_response(
            payout_state=effective_state,
            amount_cad=amount_cad,
            transfer_id=transfer_id,
        )
        logger.info(
            f"[ESCROW] escrow-path confirm for {auction_id} — payout_state={effective_state} "
            f"transfer={transfer_id or 'none'} amount={amount_cad:.2f}"
        )
        return response

    # ── Path B: transactions-only fallback (no escrow row) ────────
    # Funds MAY OR MAY NOT have been dispatched at settlement time via
    # ``services/seller_payouts.process_seller_payout``. Never assume
    # released — consult the payout state and return an accurate
    # message. This path records the pickup confirmation and enforces
    # one-time-use; it does NOT trigger a Stripe transfer and does NOT
    # cancel any pending payout obligation.
    lot_no = record.get("lot_number")
    payout_state, payout_row = await _resolve_payout_state(
        db, listing_id=record.get("listing_id") or auction_id,
        seller_id=seller_id, lot_number=lot_no,
    )

    now = datetime.now(timezone.utc).isoformat()
    result = await db.transactions.update_one(
        {
            "id": record["id"],
            # One-time-use guard: refuse if a concurrent confirm already
            # stamped this row.
            "pickup_code_confirmed_at": None,
        },
        {"$set": {
            "pickup_code_confirmed_at": now,
            "pickup_code_confirmed_by": seller_id,
            "payment_confirmed": True,
            "payment_confirmed_at": now,
            "payout_state_at_confirm": payout_state,
        }},
    )
    if result.modified_count == 0:
        raise HTTPException(status_code=409, detail={
            "error": "already_confirmed",
            "message_en": "This pickup code was already confirmed.",
            "message_fr": "Ce code a déjà été confirmé.",
        })

    # Mirror onto any paired escrow_transactions row that could exist
    # (should be zero rows in this fallback path — but if a race
    # created one after resolution, keep it consistent). Never mark
    # released without a real transfer id from the payout row.
    try:
        funds_shipped_via_prior_payout = (
            payout_state == "sent" and bool((payout_row or {}).get("stripe_transfer_id"))
        )
        esc_status = "released" if funds_shipped_via_prior_payout else "pickup_confirmed_payout_pending"
        esc_fields = {
            "escrow_status": esc_status,
            "pickup_code_entered_at": now,
            "pickup_confirmed_at": now,
            "updated_at": now,
            "payout_state": "sent" if funds_shipped_via_prior_payout else payout_state,
        }
        if funds_shipped_via_prior_payout:
            esc_fields["funds_released_at"] = now
            esc_fields["stripe_transfer_id"] = (payout_row or {}).get("stripe_transfer_id")
        await db.escrow_transactions.update_many(
            {"auction_id": auction_id, "seller_id": seller_id, "escrow_status": "held"},
            {"$set": esc_fields},
        )
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[ESCROW] escrow mirror update failed for {auction_id}: {e}")

    hammer = float(record.get("hammer_price") or record.get("amount") or 0)
    transfer_id = (payout_row or {}).get("stripe_transfer_id") if payout_state == "sent" else None
    response = _payout_state_response(
        payout_state=payout_state,
        amount_cad=hammer,
        transfer_id=transfer_id,
    )
    logger.info(
        f"[ESCROW] transaction-fallback confirm for {auction_id} — payout_state={payout_state} "
        f"transfer={transfer_id or 'none'} (no new Stripe transfer, no payout obligation removed)"
    )
    return response


async def _log_failed_attempt(db, auction_id: str, seller_id: str, attempted_code: str):
    """Log failed pickup code attempt and escalate after 5 failures."""
    await db.pickup_attempt_log.insert_one({
        "auction_id": auction_id,
        "seller_id": seller_id,
        "attempted_code": attempted_code,
        "attempted_at": datetime.now(timezone.utc).isoformat(),
    })
    failure_count = await db.pickup_attempt_log.count_documents({"auction_id": auction_id})
    if failure_count >= 5:
        await db.admin_flags.insert_one({
            "type": "pickup_code_brute_force",
            "auction_id": auction_id,
            "seller_id": seller_id,
            "failure_count": failure_count,
            "flagged_at": datetime.now(timezone.utc).isoformat(),
        })
        logger.warning(f"[ESCROW] Brute force detected for auction {auction_id} by seller {seller_id}")


async def auto_release_expired_escrows(db):
    """
    Runs every 15 minutes. Finds escrows past 48h with status "held".
    Auto-releases funds to seller without requiring code.
    """
    now = datetime.now(timezone.utc)
    expired = await db.escrow_transactions.find({
        "escrow_status": "held",
        "auto_release_scheduled_at": {"$lte": now.isoformat()},
    }).to_list(100)

    released = 0
    for escrow in expired:
        try:
            seller = await db.users.find_one(
                {"id": escrow["seller_id"]}, {"_id": 0, "stripe_connect_account_id": 1}
            )
            connect_id = (seller or {}).get("stripe_connect_account_id")
            seller_payout_cents = escrow["total_charged_cents"] - escrow["application_fee_cents"]

            transfer_id = None
            if connect_id and seller_payout_cents > 0:
                transfer = stripe.Transfer.create(
                    amount=seller_payout_cents,
                    currency="cad",
                    destination=connect_id,
                    metadata={
                        "type": "escrow_auto_release",
                        "auction_id": escrow["auction_id"],
                        "released_by": "48h_auto_release",
                    },
                )
                transfer_id = transfer.id

            await db.escrow_transactions.update_one(
                {"auction_id": escrow["auction_id"], "escrow_status": "held"},
                {"$set": {
                    "escrow_status": "auto_released",
                    "stripe_transfer_id": transfer_id,
                    "funds_released_at": now.isoformat(),
                    "updated_at": now.isoformat(),
                }},
            )
            released += 1
        except Exception as e:
            logger.error(f"[ESCROW_AUTO] Failed for {escrow.get('auction_id')}: {e}")
            await db.escrow_error_log.insert_one({
                "auction_id": escrow.get("auction_id"),
                "error": str(e),
                "occurred_at": now.isoformat(),
            })

    if released > 0:
        logger.info(f"[ESCROW_AUTO] Auto-released {released} escrows")
    return released


async def get_buyer_escrow_status(db, buyer_id: str) -> list:
    """Get all escrow transactions for a buyer.

    iter367 P0 — Union with the `transactions` collection which is where
    `finalize_auction_payment` writes pickup codes. The legacy
    `escrow_transactions` collection is only populated by the webhook
    escrow branch (rare in practice); most real escrow-in-progress rows
    live in `transactions` with `pickup_code_listing_id` set.
    """
    escrows = await db.escrow_transactions.find(
        {"buyer_id": buyer_id},
        {"_id": 0, "pickup_code": 0},
    ).sort("created_at", -1).to_list(50)

    seen = {e.get("auction_id") for e in escrows if e.get("auction_id")}
    tx_rows = await db.transactions.find(
        {"buyer_id": buyer_id, "pickup_code": {"$exists": True, "$ne": None}},
        {"_id": 0},
    ).sort("created_at", -1).to_list(50)
    for t in tx_rows:
        aid = t.get("pickup_code_listing_id") or t.get("listing_id") or t.get("auction_id")
        if not aid or aid in seen:
            continue
        confirmed_at = t.get("pickup_code_confirmed_at") or t.get("pickup_confirmed_at")
        # Buyer never sees the raw pickup_code — mask it.
        escrows.append({
            "auction_id": aid,
            "listing_id": t.get("listing_id") or aid,
            "listing_title": t.get("listing_title") or "Auction item",
            "buyer_id": buyer_id,
            "seller_id": t.get("seller_id") or t.get("pickup_code_seller_id"),
            "hammer_price_cents": int(round(float(t.get("hammer_price") or 0) * 100)),
            "total_charged_cents": int(round(float(t.get("total_charged") or t.get("hammer_price") or 0) * 100)),
            "escrow_status": "released" if confirmed_at else "held",
            "pickup_confirmed_at": confirmed_at,
            "auto_release_scheduled_at": t.get("auto_release_scheduled_at"),
            "created_at": t.get("created_at") or t.get("pickup_code_issued_at"),
            "item_type": "non_vehicle",
        })
        seen.add(aid)
    return escrows


async def get_seller_escrow_status(db, seller_id: str) -> list:
    """Get all escrow transactions for a seller (code hidden until held).

    iter367 P0 — Union with `transactions` collection (see buyer variant).
    Seller CAN see the pickup code once the escrow is held (for confirming
    pickup with the buyer in person), matching legacy behaviour.

    iter470 — Projects the actual payout state onto each row so the UI
    can distinguish ``held`` / ``pending`` / ``failed`` / ``sent``. A
    missing ``seller_payouts`` row is reported as ``unknown``; it is
    NOT reported as ``sent`` and NOT reported as ``failed``.
    """
    escrows = await db.escrow_transactions.find(
        {"seller_id": seller_id},
        {"_id": 0, "pickup_code": 0},
    ).sort("created_at", -1).to_list(50)

    seen = {e.get("auction_id") for e in escrows if e.get("auction_id")}
    tx_rows = await db.transactions.find(
        {"$or": [{"seller_id": seller_id}, {"pickup_code_seller_id": seller_id}],
         "pickup_code": {"$exists": True, "$ne": None}},
        {"_id": 0},
    ).sort("created_at", -1).to_list(50)
    for t in tx_rows:
        aid = t.get("pickup_code_listing_id") or t.get("listing_id") or t.get("auction_id")
        if not aid or aid in seen:
            continue
        confirmed_at = t.get("pickup_code_confirmed_at") or t.get("pickup_confirmed_at")
        escrows.append({
            "auction_id": aid,
            "listing_id": t.get("listing_id") or aid,
            "listing_title": t.get("listing_title") or "Auction item",
            "buyer_id": t.get("buyer_id") or t.get("pickup_code_buyer_id"),
            "seller_id": seller_id,
            "hammer_price_cents": int(round(float(t.get("hammer_price") or 0) * 100)),
            "total_charged_cents": int(round(float(t.get("total_charged") or t.get("hammer_price") or 0) * 100)),
            "escrow_status": "released" if confirmed_at else "held",
            # Seller sees the pickup code once escrow is held.
            "pickup_code": t.get("pickup_code") if not confirmed_at else None,
            "pickup_confirmed_at": confirmed_at,
            "auto_release_scheduled_at": t.get("auto_release_scheduled_at"),
            "created_at": t.get("created_at") or t.get("pickup_code_issued_at"),
            "item_type": "non_vehicle",
        })
        seen.add(aid)

    # iter470 — Project actual payout state onto every row (both
    # escrow-native and transactions-union). This gives the dashboard
    # a truthful ``payout_state`` field alongside the legacy
    # ``escrow_status``.
    for row in escrows:
        try:
            state, payout_row = await _resolve_payout_state(
                db,
                listing_id=row.get("listing_id") or row.get("auction_id"),
                seller_id=seller_id,
                lot_number=row.get("lot_number"),
            )
            row["payout_state"] = state
            if state == "sent" and payout_row:
                row["stripe_transfer_id"] = payout_row.get("stripe_transfer_id")
        except Exception as e:  # noqa: BLE001
            logger.warning(f"[ESCROW] payout state projection failed for {row.get('auction_id')}: {e}")
            row.setdefault("payout_state", "unknown")

    return escrows


async def initiate_dispute(db, escrow_auction_id: str, user_id: str, reason: str) -> dict:
    """
    Stub: marks an escrow as disputed. Future: full dispute resolution flow.
    """
    escrow = await db.escrow_transactions.find_one(
        {"auction_id": escrow_auction_id, "escrow_status": "held"},
    )
    if not escrow:
        raise HTTPException(status_code=404, detail="No active escrow found")

    if user_id not in [escrow["buyer_id"], escrow["seller_id"]]:
        raise HTTPException(status_code=403, detail="Not a party to this transaction")

    now = datetime.now(timezone.utc).isoformat()
    await db.escrow_transactions.update_one(
        {"auction_id": escrow_auction_id, "escrow_status": "held"},
        {"$set": {"escrow_status": "disputed", "updated_at": now}},
    )
    await db.escrow_disputes.insert_one({
        "auction_id": escrow_auction_id,
        "initiated_by": user_id,
        "reason": reason,
        "status": "open",
        "created_at": now,
    })
    logger.info(f"[ESCROW] Dispute opened for {escrow_auction_id} by {user_id}")
    return {"status": "disputed", "message": "Dispute has been opened. Our team will review."}
