"""
iter217 — Quebec Bill 96 listing-title compliance validator.

When a seller's listing is located in Quebec (province="QC" or region="QC"
or city="Sherbrooke"/"Montreal"/"Quebec"...) we require BOTH an English
and a French title (and description).

This is a backend hard-gate; the frontend should ALSO show inline errors.
"""
from typing import Optional
from fastapi import HTTPException


def _is_quebec_listing(region: Optional[str], city: Optional[str]) -> bool:
    r = (region or "").strip().upper()
    if r == "QC" or r == "QUEBEC":
        return True
    # City fallback only if region was not set
    if not r:
        c = (city or "").strip().lower()
        if c in ("montreal", "montréal", "quebec", "québec", "sherbrooke",
                 "laval", "gatineau", "longueuil", "saguenay", "trois-rivieres",
                 "trois-rivières", "levis", "lévis"):
            return True
    return False


def _is_blank(value: Optional[str]) -> bool:
    return value is None or not str(value).strip()


def assert_qc_bilingual_titles(
    *,
    title: Optional[str],
    title_fr: Optional[str],
    description: Optional[str] = None,
    description_fr: Optional[str] = None,
    region: Optional[str] = None,
    city: Optional[str] = None,
    content_language: Optional[str] = None,
) -> None:
    """Raises HTTP 422 with a bilingual error if a Quebec listing is
    missing the French title or description.

    The check is permissive when:
      - The seller is outside Quebec.
      - The seller explicitly typed the title in French (content_language="fr")
        — in that case the EN field is generated by translation later.
    """
    if not _is_quebec_listing(region, city):
        return

    lang = (content_language or "en").lower()

    # If the seller typed the listing in French, the French copy is `title`
    # itself, and `title_fr` may also be present. That's fine.
    if lang.startswith("fr"):
        if _is_blank(title):
            raise HTTPException(
                status_code=422,
                detail={
                    "error": "qc_french_title_required",
                    "message_en": "Quebec listings require a French title (Bill 96).",
                    "message_fr": "Les annonces québécoises doivent inclure un titre en français (Loi 96).",
                },
            )
        return

    # Seller typed in English: title_fr MUST be present.
    if _is_blank(title_fr):
        raise HTTPException(
            status_code=422,
            detail={
                "error": "qc_french_title_required",
                "message_en": "Quebec listings require a French title (Bill 96).",
                "message_fr": "Les annonces québécoises doivent inclure un titre en français (Loi 96).",
            },
        )
    if description is not None and _is_blank(description_fr):
        raise HTTPException(
            status_code=422,
            detail={
                "error": "qc_french_description_required",
                "message_en": "Quebec listings require a French description (Bill 96).",
                "message_fr": "Les annonces québécoises doivent inclure une description en français (Loi 96).",
            },
        )
