/**
 * iter361 — SafeImage (universal onError fallback → local placeholder).
 *
 * Drop-in replacement for `<img>` that guarantees a renderable image while
 * letting real user-uploaded base64 photos render naturally. Three modes:
 *
 *   1. `src` is null, undefined, or empty string → local placeholder.png
 *   2. `src` is a SHORT base64 data URL (< 5,000 chars) → local placeholder
 *      Rationale: a tiny base64 string is almost always a 1×1 transparent
 *      pixel, a broken thumbnail, or a sentinel value from a stale migration.
 *      Real photos encode to >> 5,000 characters.
 *   3. `<img>` onError fires (network failure, 404, corrupt file) →
 *      local placeholder + `onerror = null` guard against infinite loops
 *
 * iter361 changed the fallback from the old external `bidvex.com/assets/...`
 * URL (which returned 404 on production) to a locally-served
 * `/static/placeholder.png` generated by
 * `backend/scripts/generate_placeholder.py`. This eliminates the "broken
 * image icon" issue reported on the production homepage on Jul 18, 2026.
 *
 * Usage:
 *   <SafeImage src={imageUrl} alt="..." className="..." />
 */
import React, { useState, useMemo } from 'react';

// iter361 — Locally-served PNG generated by Pillow.
// Publicly accessible without auth from `frontend/public/static/placeholder.png`.
export const PLACEHOLDER_IMAGE = '/static/placeholder.png';

// Threshold under which a base64 data URL is treated as junk / placeholder
// and swapped for the branded image. 5,000 chars is comfortably above
// 1×1 transparent PNGs (~90 chars), corrupt-thumb fragments (<1KB), and
// stale migration sentinels — but well below any real listing photo.
export const BASE64_MIN_RENDERABLE_LENGTH = 5000;

const _isSafeSrc = (src) => {
  if (!src) return false;
  if (typeof src !== 'string') return false;
  const trimmed = src.trim();
  if (!trimmed) return false;
  if (trimmed.startsWith('data:')) {
    // Allow large base64 strings (real photos) to render directly.
    return trimmed.length >= BASE64_MIN_RENDERABLE_LENGTH;
  }
  return true;
};

export const SafeImage = ({ src, alt = '', onError, decoding, loading, fetchPriority, ...rest }) => {
  const initialSrc = useMemo(() => (_isSafeSrc(src) ? src : PLACEHOLDER_IMAGE), [src]);
  const [currentSrc, setCurrentSrc] = useState(initialSrc);

  // Re-evaluate when the parent updates the src prop (controlled usage).
  React.useEffect(() => {
    setCurrentSrc(_isSafeSrc(src) ? src : PLACEHOLDER_IMAGE);
  }, [src]);

  const handleError = (e) => {
    // iter361 — infinite-loop guard: null the onError before swapping src.
    // If the placeholder itself 404s (unlikely, but possible during deploy),
    // we don't retry infinitely.
    if (e?.currentTarget) {
      e.currentTarget.onerror = null;
    }
    if (e?.currentTarget?.src !== PLACEHOLDER_IMAGE
        && !e?.currentTarget?.src?.endsWith(PLACEHOLDER_IMAGE)) {
      setCurrentSrc(PLACEHOLDER_IMAGE);
    }
    if (typeof onError === 'function') {
      try { onError(e); } catch (_) { /* silent */ }
    }
  };

  return (
    <img
      {...rest}
      src={currentSrc}
      alt={alt}
      // iter358 CWV — default `decoding="async"` so image decode never
      // blocks the main thread. `loading` and `fetchPriority` are passed
      // through unchanged (caller decides — usually `lazy` on grids +
      // `eager`/`high` on hero LCP images).
      decoding={decoding || 'async'}
      loading={loading}
      fetchPriority={fetchPriority || undefined}
      onError={handleError}
      data-testid={rest['data-testid'] || 'safe-image'}
    />
  );
};

export default SafeImage;
