/**
 * iter337 — Contractor Nudges & Today's Follow-Up Targets Panel.
 *
 * Two stacked cards inside the ContractorDashboard:
 *   1. Post-call nudges (in-platform) — sentiment/compliance-driven
 *      messages generated by the backend nudge_engine scheduler.
 *   2. Today's Follow-Up Targets (max 5) — idle referred accounts,
 *      no-first-sale accounts, demos-approaching-expiry.
 *
 * Both cards are DISMISSABLE per item — dismissed items stay hidden
 * across daily refreshes (backend persistence).
 */
import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import {
  Bell, Sparkles, X, Loader2, Target, Eye, AlertTriangle, ChevronRight,
} from 'lucide-react';
import API_BASE from '../../config';
import { Card, CardContent } from '../../components/ui/card';
import { Badge } from '../../components/ui/badge';

function fmtWhen(iso, fr) {
  if (!iso) return '';
  try {
    return new Date(iso).toLocaleString(fr ? 'fr-CA' : 'en-CA', { dateStyle: 'short', timeStyle: 'short' });
  } catch { return iso; }
}

export default function ContractorNudgesPanel({ token }) {
  const { i18n } = useTranslation();
  const fr = (i18n.language || 'en').startsWith('fr');
  const [nudges, setNudges] = useState([]);
  const [targets, setTargets] = useState([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    if (!token) return;
    setLoading(true);
    try {
      const [rN, rT] = await Promise.all([
        axios.get(`${API_BASE}/ai-coach/nudges?limit=10`, {
          headers: { Authorization: `Bearer ${token}` },
        }).catch(() => ({ data: { nudges: [] } })),
        axios.get(`${API_BASE}/ai-coach/followup-targets`, {
          headers: { Authorization: `Bearer ${token}` },
        }).catch(() => ({ data: { items: [] } })),
      ]);
      setNudges(rN.data?.nudges || []);
      setTargets(rT.data?.items || []);
    } finally { setLoading(false); }
  }, [token]);

  useEffect(() => { load(); }, [load]);

  const dismissNudge = async (id) => {
    setNudges((prev) => prev.filter((n) => n.id !== id)); // optimistic
    try {
      await axios.post(
        `${API_BASE}/ai-coach/nudges/dismiss`,
        { id },
        { headers: { Authorization: `Bearer ${token}` } },
      );
    } catch (_e) {
      toast.error(fr ? 'Impossible de rejeter.' : 'Failed to dismiss.');
      load(); // revert on failure
    }
  };

  const dismissTarget = async (id) => {
    setTargets((prev) => prev.filter((t) => t.id !== id));
    try {
      await axios.post(
        `${API_BASE}/ai-coach/followup-targets/dismiss`,
        { id },
        { headers: { Authorization: `Bearer ${token}` } },
      );
    } catch (_e) {
      toast.error(fr ? 'Impossible de rejeter.' : 'Failed to dismiss.');
      load();
    }
  };

  if (loading && nudges.length === 0 && targets.length === 0) return null;
  if (!loading && nudges.length === 0 && targets.length === 0) return null;

  return (
    <div className="space-y-3" data-testid="contractor-nudges-panel">
      {/* ── Post-call nudges ── */}
      {nudges.length > 0 && (
        <Card className="border-indigo-200 bg-indigo-50" data-testid="post-call-nudges-card">
          <CardContent className="p-3 sm:p-4">
            <div className="flex items-center gap-2 mb-3">
              <Bell className="h-4 w-4 text-indigo-700" />
              <h3 className="text-sm font-semibold text-indigo-900">
                {fr ? 'Alertes après-appel' : 'Post-Call Insights'}
              </h3>
              <Badge variant="outline" className="text-[10px] border-indigo-300 text-indigo-700">
                {nudges.length}
              </Badge>
            </div>
            <ul className="space-y-2">
              {nudges.map((n) => {
                const title = fr ? (n.title_fr || n.title) : (n.title_en || n.title);
                const msg   = fr ? (n.message_fr || n.message) : (n.message_en || n.message);
                const icon  = n.type === 'ai_followup_opened' ? Eye : Sparkles;
                const Icon  = icon;
                return (
                  <li
                    key={n.id}
                    className="bg-white rounded-md border border-indigo-200 p-2 flex items-start gap-2"
                    data-testid={`nudge-${n.data?.reason || n.type}`}
                  >
                    <Icon className="h-4 w-4 text-indigo-600 mt-0.5 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-semibold text-slate-800">{title}</p>
                      <p className="text-xs text-slate-600 mt-0.5">{msg}</p>
                      <p className="text-[10px] text-slate-400 mt-1">{fmtWhen(n.created_at, fr)}</p>
                    </div>
                    <button
                      type="button"
                      onClick={() => dismissNudge(n.id)}
                      className="text-slate-400 hover:text-slate-700 flex-shrink-0"
                      title={fr ? 'Rejeter' : 'Dismiss'}
                      data-testid={`nudge-dismiss-btn-${n.id}`}
                    >
                      <X className="h-3.5 w-3.5" />
                    </button>
                  </li>
                );
              })}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* ── Today's Follow-Up Targets ── */}
      {targets.length > 0 && (
        <Card className="border-amber-200 bg-amber-50" data-testid="followup-targets-card">
          <CardContent className="p-3 sm:p-4">
            <div className="flex items-center gap-2 mb-3">
              <Target className="h-4 w-4 text-amber-700" />
              <h3 className="text-sm font-semibold text-amber-900">
                {fr ? "Cibles de suivi d'aujourd'hui" : "Today's Follow-Up Targets"}
              </h3>
              <Badge variant="outline" className="text-[10px] border-amber-300 text-amber-700">
                {targets.length}
              </Badge>
            </div>
            <ul className="space-y-2">
              {targets.map((t) => {
                const text = fr ? (t.text_fr || t.text_en) : (t.text_en || t.text_fr);
                const ReasonIcon = t.reason === 'demo_expiring' ? AlertTriangle : ChevronRight;
                const iconColor = t.reason === 'demo_expiring' ? 'text-rose-600'
                  : t.reason === 'no_first_sale' ? 'text-blue-600' : 'text-amber-600';
                return (
                  <li
                    key={t.id}
                    className="bg-white rounded-md border border-amber-200 p-2 flex items-start gap-2"
                    data-testid={`target-${t.reason}`}
                  >
                    <ReasonIcon className={`h-4 w-4 mt-0.5 flex-shrink-0 ${iconColor}`} />
                    <div className="flex-1 min-w-0">
                      <p className="text-xs text-slate-800 break-words">{text}</p>
                    </div>
                    <button
                      type="button"
                      onClick={() => dismissTarget(t.id)}
                      className="text-slate-400 hover:text-slate-700 flex-shrink-0"
                      title={fr ? 'Rejeter' : 'Dismiss'}
                      data-testid={`target-dismiss-btn-${t.id}`}
                    >
                      <X className="h-3.5 w-3.5" />
                    </button>
                  </li>
                );
              })}
            </ul>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
