/**
 * Phase 5 — BidVex Meta Pixel wrapper.
 *
 * Loads Meta's official fbevents.js snippet only when:
 *   1. REACT_APP_META_PIXEL_ID is set in the environment, AND
 *   2. The user has granted analytics-cookie consent (CASL compliance).
 *
 * Until both conditions are satisfied, calls to trackEvent / trackCustomEvent
 * are queued and replayed once the pixel boots; if consent is never granted,
 * the queue is silently dropped and no network request is made to Meta.
 *
 * `content_ids` produced here MUST match the `id` field generated by
 * `services/meta_feed_mapper.py:_content_id()` so Dynamic Product Ads can
 * match pixel events to catalog items.
 */

const PIXEL_ID = process.env.REACT_APP_META_PIXEL_ID;
// Canonical CASL consent key (Phase 5 Hotfix). The CookieConsentBanner
// writes 'true' here when analytics is accepted, 'false' on refusal /
// revocation. We also fall back to legacy keys for backward compatibility.
const CONSENT_KEY_CANONICAL = 'bidvex_analytics_consent';
const CONSENT_KEY_BANNER_STORE = 'bidvex_cookie_consent_v2';
const CONSENT_KEY_PRIMARY = 'cookieConsent';
const CONSENT_KEY_ANALYTICS = 'analytics_consent';

let _initAttempted = false;
let _initialized = false;
const _queue = [];

const TYPE_PREFIX = {
  marketplace: 'MKT',
  single: 'MKT',
  lots: 'LOT',
  multi_lot: 'LOT',
  vehicle: 'VEH',
  storage: 'STO',
};

/**
 * Build the canonical Meta content_id for a listing.
 * Format matches `services/meta_feed_mapper._content_id()`.
 */
export const buildContentId = (listingType, listingId) => {
  if (!listingId) return null;
  const prefix = TYPE_PREFIX[listingType] || 'MKT';
  return `BIDVEX-${prefix}-${listingId}`;
};

const _hasConsent = () => {
  if (typeof window === 'undefined') return false;
  try {
    // 1. Canonical CASL key — single source of truth going forward.
    const canonical = window.localStorage.getItem(CONSENT_KEY_CANONICAL);
    if (canonical === 'true') return true;
    if (canonical === 'false') return false;
    // 2. Banner store — read analytics flag out of the persisted JSON.
    const bannerRaw = window.localStorage.getItem(CONSENT_KEY_BANNER_STORE);
    if (bannerRaw) {
      try {
        const parsed = JSON.parse(bannerRaw);
        if (parsed && parsed.analytics === true) return true;
        if (parsed && parsed.analytics === false) return false;
      } catch (e) { /* fall through */ }
    }
    // 3. Legacy keys — kept for backward compatibility with older sessions.
    const v1 = window.localStorage.getItem(CONSENT_KEY_PRIMARY);
    const v2 = window.localStorage.getItem(CONSENT_KEY_ANALYTICS);
    return (
      v1 === 'accepted' ||
      v1 === 'all' ||
      v2 === 'true' ||
      v2 === 'accepted'
    );
  } catch (e) {
    return false;
  }
};

const _loadFbqScript = () => {
  /* eslint-disable */
  // Standard Meta Pixel base code — official snippet.
  !(function (f, b, e, v, n, t, s) {
    if (f.fbq) return;
    n = f.fbq = function () {
      n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
    };
    if (!f._fbq) f._fbq = n;
    n.push = n;
    n.loaded = !0;
    n.version = '2.0';
    n.queue = [];
    t = b.createElement(e);
    t.async = !0;
    t.src = v;
    s = b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t, s);
  })(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
  /* eslint-enable */
};

const _flushQueue = () => {
  if (!_initialized || typeof window === 'undefined' || !window.fbq) return;
  while (_queue.length) {
    const { name, params, custom } = _queue.shift();
    try {
      if (custom) window.fbq('trackCustom', name, params);
      else window.fbq('track', name, params);
    } catch (e) {
      // silent — pixel must never throw
    }
  }
};

/** Initializes the pixel if env var + consent are present. Safe to call repeatedly. */
export const initMetaPixel = () => {
  if (_initAttempted) return;
  if (typeof window === 'undefined') return;
  if (!PIXEL_ID) {
    // eslint-disable-next-line no-console
    console.warn('[BidVex] Meta Pixel ID not configured. Set REACT_APP_META_PIXEL_ID in .env');
    _initAttempted = true;
    return;
  }
  if (!_hasConsent()) {
    // Defer — we'll re-attempt when notifyConsentGranted() is called.
    return;
  }
  _initAttempted = true;
  try {
    _loadFbqScript();
    window.fbq('init', PIXEL_ID);
    window.fbq('track', 'PageView');
    _initialized = true;
    _flushQueue();
  } catch (e) {
    // silent — pixel must never throw
  }
};

/** Call from the cookie banner after the user accepts analytics. */
export const notifyConsentGranted = () => {
  if (typeof window !== 'undefined') {
    try {
      window.localStorage.setItem(CONSENT_KEY_CANONICAL, 'true');
    } catch (e) { /* silent */ }
  }
  _initAttempted = false; // allow re-attempt
  initMetaPixel();
};

/**
 * CASL-compliant consent revocation. Call from the cookie banner / settings
 * page when the user withdraws analytics consent. Fires fbq('consent',
 * 'revoke') immediately (Meta will stop processing events from this user),
 * persists the revocation in localStorage, and drains the in-memory queue.
 */
export const revokeConsent = () => {
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.setItem(CONSENT_KEY_CANONICAL, 'false');
  } catch (e) { /* silent */ }
  try {
    if (window.fbq) window.fbq('consent', 'revoke');
  } catch (e) { /* silent — pixel must never throw */ }
  // Drop any queued (un-flushed) events so they can never fire.
  _queue.length = 0;
  _initialized = false;
};

const _enqueue = (name, params, custom = false) => {
  if (typeof window === 'undefined') return;
  if (_initialized && window.fbq) {
    try {
      if (custom) window.fbq('trackCustom', name, params);
      else window.fbq('track', name, params);
    } catch (e) {
      // silent
    }
    return;
  }
  // Queue until init completes (consent or env arrives later)
  _queue.push({ name, params, custom });
  if (_queue.length > 50) _queue.shift(); // bound the queue
};

export const trackEvent = (eventName, params = {}) => _enqueue(eventName, params, false);
export const trackCustomEvent = (eventName, params = {}) => _enqueue(eventName, params, true);

// ── Convenience helpers used across the app ──────────────────────────
export const trackViewContent = (listing) => {
  if (!listing || !listing.id) return;
  const price =
    (typeof listing.current_bid === 'number' && listing.current_bid > 0 && listing.current_bid) ||
    (typeof listing.current_price === 'number' && listing.current_price > 0 && listing.current_price) ||
    (typeof listing.starting_bid === 'number' && listing.starting_bid > 0 && listing.starting_bid) ||
    (typeof listing.starting_price === 'number' && listing.starting_price > 0 && listing.starting_price) ||
    0;
  const contentType = listing.listing_type === 'vehicle' ? 'vehicle' : 'product';
  trackEvent('ViewContent', {
    content_ids: [buildContentId(listing.listing_type, listing.id)],
    content_type: contentType,
    content_name: listing.title || '',
    content_category: listing.category || '',
    value: parseFloat(Number(price).toFixed(2)),
    currency: 'CAD',
    city: listing.city || listing.location?.city || '',
    region: listing.region || listing.province || listing.location?.province || '',
    country: 'CA',
  });
};

export const trackAddToWishlist = (listing, price) => {
  if (!listing || !listing.id) return;
  trackEvent('AddToWishlist', {
    content_ids: [buildContentId(listing.listing_type, listing.id)],
    content_type: 'product',
    value: parseFloat(Number(price || 0).toFixed(2)),
    currency: 'CAD',
  });
};

export const trackPurchase = ({ listingId, listingType, totalCharged }) => {
  if (!listingId) return;
  trackEvent('Purchase', {
    content_ids: [buildContentId(listingType, listingId)],
    content_type: 'product',
    value: parseFloat(Number(totalCharged || 0).toFixed(2)),
    currency: 'CAD',
    num_items: 1,
  });
};

export const trackSearch = ({ searchString, category, city, province }) => {
  trackEvent('Search', {
    search_string: searchString || '',
    content_category: category || '',
    city: city || '',
    region: province || '',
    country: 'CA',
  });
};

// Test-only / debugging hook
export const __debug = {
  pixelId: PIXEL_ID,
  isInitialized: () => _initialized,
  queueLength: () => _queue.length,
};
